### ISSUE TITLE
Search algorithm doesn't works properly

### ISSUE THREAD

**Issue by iamthevoid** [iWedmak/oneom-website#10]
If search string contains spaces, search algorithm works incorrect:
request using URL Encoding:
{"serials":[],"text":"the+big"}
{"serials":[],"text":"the+bi"}
{"serials":[],"text":"the+b"}
{"serials":[],"text":"The+Big"}

but if i ask for "bang theory" i get right result (12 results). 
If enter "the" or "big" separately - search works.

**Comment by iWedmak** [comment]
kinda fixed, buuuuut we need something like sphinx on serve side, but i cant install it on this point
